version: "3.9"
services:
  coordinator:
    image: mutual_exclusion:latest
    command: "gunicorn --bind=0.0.0.0:5000 -w 1 --threads 5 --keep-alive 5 --timeout 120 coordinator:app"
    
  client1:
    image: mutual_exclusion:latest
    command: "python client.py"
    environment:
      - coordinator_url=http://coordinator:5000
      - client_id=1

  client2:
    image: mutual_exclusion:latest
    command: "python client.py"
    environment:
      - coordinator_url=http://coordinator:5000
      - client_id=2

